### ISSUE TITLE
界面改进建议

### ISSUE THREAD

**Issue by fcwys** [ChinaMoli/AmoliCloud#1]
1、首页目录列表太紧凑了不是很美观
2、 希望添加上返回上一级的按钮
3、手机版文件目录不显示大小和时间更直观
4、增加搜索框（仅当前页面，非全局）
希望AmoliCloud做得更好，谢谢！

**Comment by ChinaMoli** [comment]
后期有改动的打算
因为有了面包屑导航，所以加入返回上一级显得有点多余
手机版不显示日期可以，但是大小还是必须显示的，后面会改动
搜索框 暂时用着Ctrl+F
感谢你的反馈

**Comment by fcwys** [comment]
谢谢！
