### ISSUE TITLE
【Bug】首页无法查看图片

### ISSUE THREAD

**Issue by cattomgithub** [ChinaMoli/AmoliCloud#3]
首页无法加载图片，具体问题如图。
![QQ截图20190807212952](https://user-images.githubusercontent.com/16714790/62626692-8620c300-b95a-11e9-86dc-fdb28141e8d3.png)

**Comment by ChinaMoli** [comment]
这个是因为后台设置的出现的问题
目录名称，从根目录开始，必须以"/"结尾，例如down/，text/img/
留空即为根目录
你这个问题 肯定是因为你设置的目录的时候 在前面加入/

**Comment by ChinaMoli** [comment]
@cattomgithub 如果没有其他，那么 Issue 将被关闭。
