### ISSUE TITLE
错误信息：非法访问！

### ISSUE THREAD

**Issue by tamakyi** [ChinaMoli/AmoliCloud#4]
最新版本文件下载验证会经常弹出错误信息：非法访问！的提示，或者在验证界面点击右侧那个闪动的蓝点会跳过验证然后也会弹出错误信息：非法访问！的提示。
[https://test.tamakyi.club/webdisk](url)
附链接

**Comment by ChinaMoli** [comment]
感谢你的反馈，这个确实是我测试的时候没有遇到过的问题，请等待解决，如果方便请加一下群然后在群里@群主，方便我及时发现问题，感谢！

**Comment by ChinaMoli** [comment]
BUG已经修复，结合极验官方文档得出结论，出现此BUG的大概原因可能因为你私自修改验证ID或者验证KEY，当时判断没有做全面，已经加入判断，如果私自修改ID出现宕机，程序会进入宕机模式，这个问题会在下个版本修复。
目前解决方案就是，你用最新源码替换掉app/class/Geetestlib.class.php，即可解决

**Comment by ChinaMoli** [comment]
@tamakyi 如果没有其他问题， Issue 将被关闭。
