### ISSUE TITLE
功能建议&BUG

### ISSUE THREAD

**Issue by cnlyzy** [ChinaMoli/AmoliCloud#7]
## 需求
- 支持拖拽上传
- 文件夹上传(包含子目录等)
- 文件夹管理(下载,删除)
- 文件重命名

## 建议
- 文件分享短连接方法删除(新浪报错403),也没必要缩短,反而增加请求时长
- geetest配置入口,你的私钥暴露了
- 你网站数据丢失导致程序内的超链接404,建议删除

## MORE
1.界面优化, 2.多账户, 3.多种存储类型同时可用 ...

感谢开源分享

**Comment by ChinaMoli** [comment]
后期会加入你说的的需求
用短链的目的是为了不用数据库后期考虑使用SQLite
geetest是为了直接让你们上手使用，所以内置的我自己的
数据丢失是因为服务器过期了 没续费
页面后期会优化
多账户是不会加入的，因为定位是私有云
后续会增加七牛这些
这段时间在忙其他项目所以没空更新
感谢你的建议以及反馈

**Comment by cnlyzy** [comment]
> 用短链的目的是为了不用数据库后期考虑使用SQLite

短连接和长连接跟数据库有啥关系?要做分享链接管理?

原链接形式`https://example.com/share.php?s=https://example.com?xxx`
建议改成`https://example.com/s/xxx`

另外点击下载时候如果网站是`https`而返回的下载链接是`http`协议,浏览器会拦截,可以在接口输出时候处理下链接,做个协议跟随`//`

**Comment by ChinaMoli** [comment]
链接形式需要加入伪静态，怕用户不会设置所以就没有改，其它的意见在下个版本会加入
