### ISSUE TITLE
这个只能在后台文件管理那里分享吗？

### ISSUE THREAD

**Issue by hl668** [ChinaMoli/AmoliCloud#8]
我在后台那里点击了分享，一直转圈，链接显示不出来。还有，文件的上传大小限制怎么修改。另外非常感谢大佬提供这个轻巧的程序，很喜欢。

**Comment by ChinaMoli** [comment]
分享功能最近有问题，文件大小 可以百度搜索php上传限制修改，感谢你的喜欢
